// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// You will also need to install the AutoT4 Visual Studio extension so that the .tt file will re-generate the .cs file on a build
// 

using System.Reflection;

// The version is Major.Year.MonthDay.HourMinute(Tens of)Seconds
[assembly: AssemblyVersion("3.2020.1106.13323")]
[assembly: AssemblyFileVersion("3.2020.1106.13323")]

